[playdb]
title = "플레이DB ─ 매거진"
url = "http://www.playdb.co.kr/magazine/magazine_temp.asp?kindno=ALL"
entrySelector = "div.list ul li"
titleSelector = "strong a"
linkSelector = "span.thumb a"
imageSelector = "span.thumb a img"
contentSelector = "span.txt"

[bugs_musicpost]
title = "벅스 ─ 뮤직포스트"
url = "https://music.bugs.co.kr/musicpost"
entrySelector = "ul.list.tileView.specialList li"
titleSelector = "a[class^='title']"
linkSelector = "a"
imageSelector = "a.thumbnail.hyrend img"
contentSelector = "a.category"

[genie]
title = "지니 ─ 매거진"
url = "https://genie.co.kr/magazine"
entrySelector = "div.list-normal ul.clearfix li"
titleSelector = "p.title"
linkSelector = "a"
imageSelector = "div.cover img"
contentSelector = "div.info strong.category"

[vibe]
title = "VIBE ─ 매거진"
url = "https://vibe.naver.com/magazines"
entrySelector = "ul.mag_list li.list_item"
titleSelector = "a.title"
linkSelector = "div.info a"
imageSelector = "div.thumb img"
contentSelector = "div.sub span.item:nth-child(1)"
waitForSelector = "li.list_item"
onFail = "stale"

[vibe_top]
title = "VIBE ─ 매거진"
url = "https://vibe.naver.com/magazines"
entrySelector = "div.link_wrap"
titleSelector = "strong.title"
linkSelector = "div.link_wrap a.link"
imageSelector = "div.thumb img"
contentSelector = "div.info"
waitForSelector = "div.link_wrap"
onFail = "stale"
